apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-api-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: traefik
spec:
  tls:
    - hosts:
        - devopsapi.georgesoares.dev
      secretName: devops-api-tls
  rules:
    - host: devopsapi.georgesoares.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devops-api-service
                port:
                  number: 80
