name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir e publicar imagem no Docker Hub
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)  # Gera um timestamp único
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/devops-api:$IMAGE_TAG
          
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Atualizar manifestos no repositório Git do ArgoCD
        run: |
          git clone https://${{ secrets.GIT_REPO_TOKEN }}@github.com/George-b1t/devops-api.git
          cd k8s

          # Atualiza a imagem no arquivo `kustomization.yaml`
          sed -i "s|newTag: .*|newTag: $IMAGE_TAG|" k8s/kustomization.yaml

          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git add k8s/kustomization.yaml
          git commit -m "Atualizando imagem para devops-api:$IMAGE_TAG"
          git push
