name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Modifique para o nome da sua branch, se necessário

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir e publicar imagem no Docker Hub
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/devops-api:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-api:latest
